name: Pull request to main workflow
run-name: Pull request to main by @${{ github.actor }}

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Create Scratch Org
        run: |
          echo ${{ vars.SF_HUB_SFDXURL }} > devhub.txt
          sf org login sfdx-url --sfdx-url-file devhub.txt --alias DevHub --set-default-dev-hub
          sf org create scratch --definition-file config/project-scratch-def.json --alias TestOrg --set-default --no-track-source --duration-days 1
          sf project deploy start --target-org TestOrg
      
      - name: Run Tests
        run: |
          sf apex run test --target-org TestOrg --wait 10 --code-coverage
          sf data query --query "SELECT PercentCovered FROM ApexOrgWideCoverage" --use-tooling-api --target-org TestOrg --json > coverage.json
          
          APEX_COVERAGE=$(jq -r '.result.records[0].PercentCovered' coverage.json)

          echo "Org Wide Test Coverage = "$APEX_COVERAGE

          if [ ${APEX_COVERAGE} -lt 80 ]; then
            echo "The Apex test run coverage is $APEX_COVERAGE - less than 80%"
            exit 1
          fi
        
      - name: Delete Scratch Org
        run: |
          echo "Deleting scratch org..."
          sf org delete scratch --target-org TestOrg --no-prompt