name: Pull request to main workflow
run-name: Pull request to main by @${{ github.actor }}

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Create org and run tests
        uses: actions/checkout@v3
        run: |
          echo ${{ vars.SF_HUB_SFDXURL }} > devhub.txt
          sf org login sfdx-url --sfdx-url-file devhub.txt --alias DevHub --set-default-dev-hub

          echo "Creating scratch org..."
          sf org create scratch --definition-file config/project-scratch-def.json --alias TestOrg --set-default --no-track-source --duration-days 1
          sf project deploy start --target-org TestOrg
          
          echo "Running tests..."
          sf apex run test --target-org TestOrg --wait 10 --code-coverage --output-dir test-coverage

          if [ ! -r test-coverage/test-run-id.txt ]; then
            echo "\nFATAL ERROR: Could not load test-coverage result files. Files not found.\n"
            exit 1
          fi

          APEX_JOB_ID=$(<test-coverage/test-run-id.txt)
          METHODS_FAILED=($(jq -r '.summary.failing' test-coverage/test-result-$APEX_JOB_ID.json))
          APEX_COVERAGE=($(jq -r '.summary.orgWideCoverage' test-coverage/test-result-$APEX_JOB_ID.json))

          echo "Org Wide Test Coverage = "$APEX_COVERAGE

          if [ $METHODS_FAILED -lt 0 ]; then
            echoErrorMsg "$METHODS_FAILED test method(s) failed, please check above for further details."
            exit 1
          fi

          if [ ${APEX_COVERAGE%\%} -lt 80 ]; then
            echoErrorMsg "The Apex test run coverage is $APEX_COVERAGE - less than 80%"
            exit 1
          fi
          
          echo "Deleting scratch org..."
          sf org delete scratch --target-org TestOrg --no-prompt